### ISSUE TITLE
PillToggle's item prop should take in array of objects

### ISSUE THREAD

**Issue by sanghun89** [Insightpool/orchestra#10]
Referring to the PR here https://github.com/Insightpool/orchestra/pull/9

Taking in array of objects, with `name` and `value` as a property, might be a better approach for two reasons:
- When you want internal `value` is different from what you are displaying in each "pill" item
- When you consider the order of the pill toggle to be important.

So the new proposed format of the `items` prop is:
```
items: React.PropTypes.arrayOf(
    React.PropTypes.shape({
        active: React.PropTypes.bool,
        name: React.PropTypes.string,
        notifications: React.PropTypes.array,
        value: React.PropTypes.oneOfType(
            React.PropTypes.string,
            React.PropTypes.number
        )
    })
).isRequired;
```

**Comment by sethen** [comment]
This is done and has been merged into the master branch in commit c9f59ff2433e2dbcc78bc8cb63eacf6fc9a0154c ... Thanks!
