### ISSUE TITLE
Allow index.js when using imports

### ISSUE THREAD

**Issue by sanghun89** [Insightpool/orchestra#11]
The current application is doubled in size due to the fact that we are always giving out a built file as an export. I believe implementing something like an `index.js` where it has the option to import the script that is not built yet so it can use any of the shared libraries (like react). The reason for this is because with orchestra introduced, there are some duplicates of required libraries that is shared by both the application and orchestra, causing our app size to double (appr 5.8mb).

I know the initial approach was to be universally used, but when I see other npm libraries they give both the option to use the built script if they are using it in the `script` tag, or allow `index.js` to import the non-compiled scripts to share any common node modules with the current application.

**Comment by sethen** [comment]
Yeah, this is fine.  I believe this was already something I was going to do but just never got around to it.

**Comment by sethen** [comment]
Actually, this doesn't need to happen.  Webpacks `externals` option can take these out of the final build and leave it up to the host application provide the dependencies.
