### ISSUE TITLE
Orchestra Checkbox styles collide with existing checkbox styles and state doesn't change properly

### ISSUE THREAD

**Issue by JonathanBruce** [Insightpool/orchestra#14]
## Issue
* inside orch-checkbox there is a classname of checkbox which collides with existing styles so I sought to make it more unique which resolved an issue I have tested locally.
* The property for checked can't get set by passing properties and I was wondering why there is internal state and what the point is of a checked property if it's only to modify the initial checked state.

The above described is an issue because Ryan's tailored audience component has style collisions with the checkbox and the tailored audience card can be enabled via clicking not on the checkmark. Thereby activating the selected classes on the card but the checkbox component ignores the checked property because it is not set by redux state it only changes when it uses setState()

## Proposed Solution 
* more specific classname
* use default property static and allow maintain checked in redux state rather than internally.

**Comment by sethen** [comment]
The newest version of Orchestra has removed the state for the checkbox completely.  I am not exactly sure why that was there after further inspection...  I felt like there may have been a reason there, but there isn't any longer.

You've always been able to pass the `checked` property to the checkbox, this has always been true.

I am not in favor of changing the classname of the `CheckBox` component.  It looks like in the application there is a global `checkbox` property in the `tailored-audience` class.  I would recommend, rather, taking out that classname to avoid the clashing there.  This is more beneficial because then you're removing old code that we no longer need in the application.

**Comment by JonathanBruce** [comment]
is it released? cause I removed orchestra and reinstalled and I don't see any differences as of 19 minutes after your commit.

I agree with taking out that code but to be thorough wouldn't it behoove us to remove the orch-CheckBox.CheckBox and change it to something specific or remove the 2 checkboxes. 

Doesn't having a general name like .checkbox in orchestra risk always running into unexpected collisions?

**Comment by JonathanBruce** [comment]
also I'm seeing `box-sizing: none;` on the checkbox which is an invalid property. It needs to be content-box. or else this happens
<img width="214" alt="screen shot 2016-08-19 at 10 51 02 am" src="https://cloud.githubusercontent.com/assets/1743411/17813863/2000abf4-65fb-11e6-9189-e510c133bb34.png">

**Comment by sethen** [comment]
No, it doesn't really behoove us to change the name of the class from `checkbox` to something else.  Collisions can happen but that's not Orchestra's concern.  It's the concern of the application that uses the tool to do the right thing.  The framework shouldn't change because someone made a bad decision in their naming process.

`box-sizing: none` is not being added to the component in Orchestra, this is coming from somewhere else.  If you look at the properties in the example page you can see no `box-sizing` property exists.

**Comment by JonathanBruce** [comment]
none isn't a valid property value for box-sizing

**Comment by JonathanBruce** [comment]
well box-sizing: border-box causes this to happen.

**Comment by JonathanBruce** [comment]
there's no .checkbox class in the application anymore I renamed all of them and marked them for deletion.

This is what I can see in the class preview

```orch-checkbox .checkbox.checked, .orch-checkbox .checkbox.checked:hover {
    border: 2px solid transparent;
    border-radius: 3px;
    border-color: #4d99c4;
    box-sizing: none;
    color: #235f81;```

**Comment by JonathanBruce** [comment]
Looks like maybe one of your mixin classes could be applying this?

**Comment by sethen** [comment]
Where is this coming from?  `box-sizing: none` isn't defined anywhere in the Orchestra code.

**Comment by JonathanBruce** [comment]
it's not coming from the app. Looking at the compiled orchestra files it's definitely in orchestra.

**Comment by JonathanBruce** [comment]
<img width="1440" alt="screen shot 2016-08-19 at 2 35 33 pm" src="https://cloud.githubusercontent.com/assets/1743411/17820312/3455e654-661a-11e6-806a-12eb5ff670e3.png">

**Comment by sethen** [comment]
This is something being added to the build but not anything that Orchestra is doing intentionally.  I can try to investigate this but that's very bizarre that it's being added to the final bundle by webpack.

**Comment by JonathanBruce** [comment]
:o interesting. Well I guess I'll just forcibly add content-box to override the inherited `box-sizing: border-box` that is breaking the orchestra checkbox?

**Comment by sethen** [comment]
Well, hold on... If you look at the `dist` directory in Orchestra and do a search for `box-sizing: none` there aren't any matches.  Which leads me to believe this is still something the client application is doing.

**Comment by JonathanBruce** [comment]
/Users/jonathanbruce/Documents/work/orchestra/tests/functional/base/SecondaryButton.entry.js:

**Comment by JonathanBruce** [comment]
I see it in these guys which makes little to no sense.

**Comment by JonathanBruce** [comment]
also in /Users/jonathanbruce/Documents/work/orchestra/example/example.build.js:

**Comment by sethen** [comment]
But neither of those files have anything to do with the final build.  The `box-sizing: none1

**Comment by sethen** [comment]
Neither of those files have anything to do with the final build.  `box-sizing: none` is not being added to the final bundle for Orchestra.

**Comment by JonathanBruce** [comment]
I removed all of the CSS from the app, and it's still there

**Comment by JonathanBruce** [comment]
<img width="1440" alt="screen shot 2016-08-19 at 2 48 46 pm" src="https://cloud.githubusercontent.com/assets/1743411/17820694/10e95d02-661c-11e6-8355-87ad96533f94.png">
also lel this image

**Comment by sethen** [comment]
Have you taken a look at the the `dist/ui.js` file in Orchestra?  That's what is being imported.  I can't find `box-sizing: none` anywhere in that file.

**Comment by JonathanBruce** [comment]
yeah I see it in ui.build.js

**Comment by JonathanBruce** [comment]
<img width="1440" alt="screen shot 2016-08-19 at 3 21 50 pm" src="https://cloud.githubusercontent.com/assets/1743411/17821640/ac4b3938-6620-11e6-94b2-ba5921bd0eb4.png">

this is ui.build.js

**Comment by JonathanBruce** [comment]
bump

**Comment by sethen** [comment]
That's interesting... I don't know what that's being added but I can take a look.

**Comment by sethen** [comment]
I found the issue... I think it was a flubbed attribute value added to the mixin.  Fixing now.

**Comment by sethen** [comment]
Alright, this `box-sizing:none` is no longer showing up in the `ui.build.js` file any longer.  Closing this issue.
