### ISSUE TITLE
Container component documentation.

### ISSUE THREAD

**Issue by colbydehart** [Insightpool/orchestra#19]
~~Currently the container components, the individual grid components (`<Twelve>`, `<Six>`) are set to fixed widths. It would be nice if they were somehow set to percentages so that we could nest these components within a `<Container>` component, which could still have a fixed static width, so that as long as you set grid components as the first child of either a `Container` or another grid component, everything would still work. This would let us set up complex layouts (like in aggregate analytics on the client app) like this.~~

```
<Container>
  <Three className='sidebar'> { ... } </Three>
  <Nine>
    // Either like this, where the inside of the `Nine` component
    // has 12 segments inside of it. (5 + 7 = 12)
    <Five> Some Small Content </Five>
    <Seven> Some Larger Content </Seven>

    // Or like this, where we can split up the 9 segments
    // inside the `Nine compenents ( 4 + 5 = 9)
    <Four> Some Small Content </Four>
    <Five> Some Larger Content </Five>
  </Nine>
</Container>
```

~~This will allow us to simplify a lot of the application's layout by converting basically every layout aspect of the site into orchestra component as well as more quickly piece together new features with more complex layouts.~~

**Comment by sethen** [comment]
You can already do that.  For instance, considering the following code:

```
<Twelve>
    <Six alpha>Alpha</Six>
    <Six omega>Omega</Six>
</Twelve>
```

This will work.  The idea is that any column you have that needs to be nested can be within other columns.  You just need to add `alpha` and `omega` to the first and last columns that are nested respectively.

The prop types on these columns are of `string` though and those could probably be changed to `boolean` to be more concise.

There is no documentation around the grid stuff, so I can make sure I add that.

**Comment by sethen** [comment]
I just added the documentation, you should be all set.  Closing this.
